# Plugins
plugins: [jekyll-paginate, jekyll-gist]

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Phillip J. Wolfram
tagline:          'Coastal ocean scientist'
description:      'Coastal ocean science'
url:              http://pwolfram.github.io
baseurl:          /

author:
  name:           'Phillip J. Wolfram'
  url:            https://pwolfram.github.io

paginate:         5
paginate_path: "page:num"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/pwolfram/pwolfram.github.io

profile:          https://github.com/pwolfram/
