# Plugins
plugins: [jekyll-paginate, jekyll-gist]

# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Phillip J. Wolfram
tagline:          'Personal website'
description:      'The personal website of Phillip J. Wolfram'
url:              /
baseurl:          http://pwolfram.github.io

author:
  name:           'Phillip J. Wolfram'
  url:            http://pwolfram.github.io

paginate:         5
paginate_path: "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/pwolfram/pwolfram.github.io
